export const sneakerData = [
  {
    id: 1,
    name: "JORDAN 1 HIGH OG SPIDER-MAN ACROSS THE SPIDER-VERSE",
    price: 24000,
    desc: "Nike and Jordan Brand are revisiting the Spider-Verse once again for their second collaboration featuring Spider-Man and have introduced the Air Jordan 1 High OG Spider-Man Across the Spider-Verse as part of this release.",
    img: "https://crepdogcrew.com/cdn/shop/files/AirJordan1RetroHighOGSPNEXTCHAPTER_800x.png?v=1683613375",
  },
  {
    id: 2,
    name: "NIKE DUNK LOW WHITE BLACK (PANDA)",
    price: 12499,
    desc: "The '80s basketball favorite makes a return with glossy layers and iconic hues evocative of college teams. Crafted for the courts but even an urban star, the '80s. The Nike Dunk Low brings '80s style to the streets with its famous basketball style, while its low, cushioned neck allows you to wear it anywhere in optimal comfort.",
    img: "https://crepdogcrew.com/cdn/shop/files/image_8f504660-fd59-4e51-9f60-97c58eb56af9_800x.jpg?v=1697461668",
  },
  {
    id: 3,
    name: "JORDAN 1 RETRO LOW GOLF TRAVIS SCOTT NEUTRAL OLIVE",
    price: 110000,
    desc: "Get legit Air Jordan High, Air Jordan Mid, Air Jordan Low, and more limited edition sneakers.",
    img: "https://crepdogcrew.com/cdn/shop/files/1_7bc8118c-93a6-43a2-bfd3-de2f95d7a2f9_800x.png?v=1697181311",
  },
  {
    id: 4,
    name: "JORDAN 4 RETRO RED CEMENT",
    price: 16000,
    desc: "The Jordan 4 Retro Red Cement comes with a fresh take on a traditional hue with flaming red accents all throughout the design. For those not afraid to stand out, Jordan Brand didn't hold back with this release, offering a strong statement piece.",
    img: "https://crepdogcrew.com/cdn/shop/files/1_0bbfd1f2-f128-4914-a209-eb5496b76c1c_800x.png?v=1693645784",
  },
  {
    id: 5,
    name: "JORDAN 3 RETRO SP JBALVIN MEDELLÍN SUNSET",
    price: 49000,
    desc: "Color Shown: MULTI-COLOR/MULTI-COLOR.",
    img: "https://crepdogcrew.com/cdn/shop/files/17_d2af19d1-ebda-49bb-98ba-a7eededcf92c_800x.png?v=1695477577",
  },
  {
    id: 6,
    name: "NIKE DUNK LOW TRIPLE PINK (GS)",
    price: 19000,
    desc: "The Nike Dunk Low Triple Pink, sometimes referred to as the Barbie updates the traditional design of the vintage Nike basketball sneaker. It has a full leather construction and is finished in three different colours of pink. The overlay is a light shade of pink that contrasts significantly with the light pink foundation.",
    img: "https://crepdogcrew.com/cdn/shop/products/NikeDunkLowTriplePink_GS_800x.jpg?v=1673078286",
  },
  {
    id: 7,
    name: "BMW SHIRT TYPE 3 - PALE ROSE",
    price: 3900,
    desc: "The BMW shirt has an underlapped conventional shirt pocket with a reverse box pleat detail to match the slacks.",
    img: "https://crepdogcrew.com/cdn/shop/products/IMG_7685_df357627-ac7c-408b-868c-da5786b77849_800x.jpg?v=1667993950",
  },
  {
    id: 8,
    name: "BMW PANT TYPE 3 - PALE ROSE",
    price: 5000,
    desc: "BMW pants have a textured knit fabric comprised of fine polyester yarn and a Welt pocket feature for more comfort in your formals.",
    img: "https://crepdogcrew.com/cdn/shop/products/IMG_7780_1f285c05-e03b-44ee-b4ef-6d45ee8262a0_800x.jpg?v=1667994629",
  },
  {
    id: 9,
    name: "HOLSTER BAG - PYTHON BLUE",
    price: 4700,
    desc: "The Holster Bag is designed to be a conversation starter and fits urban lifestyles perfectly. It can be worn as a holster and also as a sling bag by removing the waist strap. Neck and waist straps can be adjusted to find the right fit. The Holster comes equipped with a quick access phone pocket, sunglass loop and a dog hook for your belongings. Wear it with your usual oversized fits or over a well fitted suit.",
    img: "https://crepdogcrew.com/cdn/shop/products/ProductImages-BGRemoveTemplate_4_800x.png?v=1672989268",
  },
];
